baseURL = 'https://example.org/'
languageCode = 'zh'
title = '杂货店老板'
theme = 'hugo-book'
hasCJKLanguage = true
defaultContentLanguage = 'zh'

[params]
    BookTheme = 'auto'
    BookMenuBundle = '/menu'
    BookFavicon = 'favicon_v1.png'
    BookLogo = 'favicon_v1.png'

[outputs]
    home = ["HTML", "RSS"]
