baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title = '杂货店老板'
theme = 'hugo-book'
hasCJKLanguage = true

[params]
    BookTheme = 'auto'
    BookMenuBundle = '/menu'
    BookFavicon = 'favicon_v2.png'
    BookLogo = 'favicon_v2.png'
