baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title = 'Tomato keeper'
theme = 'hugo-book'
hasCJKLanguage = true

[params]
    BookTheme = 'auto'
    BookLogo = 'logo.png'
    BookMenuBundle = '/menu'
